name: flutter_chat_ui

version: 1.5.2



environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.1.6
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  flutter_chat_types: ^3.2.2
  meta: ^1.3.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
